// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Context;

#nullable disable

namespace backend.Migrations.V1
{
    [DbContext(typeof(DbContextBrainlyPhysio))]
    partial class DbContextBrainlyPhysioModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.User.Account", b =>
                {
                    b.Property<int>("IdAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_cont");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAccount"));

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("cod_activare");

                    b.Property<DateTime>("ConfirmationLinkHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ora_link")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasColumnName("descriere");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<string>("ImageHash")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("image_hash");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("cale_imagine");

                    b.Property<sbyte>("IsVerified")
                        .HasColumnType("tinyint")
                        .HasColumnName("verificat");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("nume");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("parola");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("nr_telefon");

                    b.Property<string>("Prename")
                        .HasMaxLength(70)
                        .HasColumnType("varchar")
                        .HasColumnName("prenume");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar")
                        .HasColumnName("rol");

                    b.HasKey("IdAccount");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("INDEX_EMAIL");

                    b.ToTable("conturi", (string)null);
                });

            modelBuilder.Entity("backend.Models.User.Location", b =>
                {
                    b.Property<int>("IdLocation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_locatie");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLocation"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("oras");

                    b.Property<string>("County")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("judet");

                    b.HasKey("IdLocation");

                    b.ToTable("locatii", (string)null);
                });

            modelBuilder.Entity("backend.Models.User.MemberQuality", b =>
                {
                    b.Property<int>("IdMemberQuality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_calitate_membru");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMemberQuality"));

                    b.Property<int>("IdMember")
                        .HasColumnType("int")
                        .HasColumnName("id_membru");

                    b.Property<int>("IdQuality")
                        .HasColumnType("int")
                        .HasColumnName("id_calitate");

                    b.HasKey("IdMemberQuality");

                    b.HasIndex("IdMember");

                    b.HasIndex("IdQuality");

                    b.ToTable("calitati_membru", (string)null);
                });

            modelBuilder.Entity("backend.Models.User.OperationPlace", b =>
                {
                    b.Property<int>("IdOperationPlace")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_loc_operare");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOperationPlace"));

                    b.Property<int>("IdAccount")
                        .HasColumnType("int")
                        .HasColumnName("id_membru");

                    b.Property<int>("IdLocation")
                        .HasColumnType("int")
                        .HasColumnName("id_locatie");

                    b.HasKey("IdOperationPlace");

                    b.HasIndex("IdAccount");

                    b.HasIndex("IdLocation");

                    b.ToTable("locuri_de_operare", (string)null);
                });

            modelBuilder.Entity("backend.Models.User.Quality", b =>
                {
                    b.Property<int>("IdQuality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_calitate");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdQuality"));

                    b.Property<string>("QualityName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nume_calitate");

                    b.HasKey("IdQuality");

                    b.ToTable("calitati", (string)null);
                });

            modelBuilder.Entity("backend.Models.User.RememberUser", b =>
                {
                    b.Property<int>("IdSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_sesiune");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSession"));

                    b.Property<DateTime>("ExpiresAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at")
                        .HasDefaultValueSql("(NOW() + INTERVAL 30 DAY)");

                    b.Property<int>("IdAccount")
                        .HasColumnType("integer")
                        .HasColumnName("id_cont");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("sesiune_stocata");

                    b.HasKey("IdSession");

                    b.HasIndex("IdAccount")
                        .IsUnique();

                    b.ToTable("sesiuni", (string)null);
                });

            modelBuilder.Entity("backend.Models.Utils.Announce", b =>
                {
                    b.Property<int>("IdAnnounce")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_anunt");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAnnounce"));

                    b.Property<string>("AboutCourse")
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("descriere_curs");

                    b.Property<DateTime>("ComingDate")
                        .HasColumnType("date")
                        .HasColumnName("data_venire");

                    b.Property<string>("ContactPhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("nr_telefon_contact");

                    b.Property<int>("CourseDuration")
                        .HasColumnType("int")
                        .HasColumnName("durata_curs");

                    b.Property<string>("CourseImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("cale_imagine_curs");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar")
                        .HasColumnName("titlu_curs");

                    b.Property<sbyte?>("EmcPoints")
                        .HasColumnType("tinyint")
                        .HasColumnName("puncte_emc");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("data_expirare");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("format");

                    b.Property<DateTime>("LeavingDate")
                        .HasColumnType("date")
                        .HasColumnName("data_plecare");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("locatie");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("pret");

                    b.Property<string>("Trainers")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar")
                        .HasColumnName("traineri");

                    b.HasKey("IdAnnounce");

                    b.ToTable("anunturi", (string)null);
                });

            modelBuilder.Entity("backend.Models.Utils.CourseSection", b =>
                {
                    b.Property<int>("IdCourseSection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_sectiune_curs");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCourseSection"));

                    b.Property<int>("CourseSectionOrder")
                        .HasColumnType("int")
                        .HasColumnName("ordine_sectiune");

                    b.Property<int>("IdAnnounce")
                        .HasColumnType("int")
                        .HasColumnName("id_anunt");

                    b.Property<string>("SectionTitle")
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasColumnName("titlu_sectiune");

                    b.HasKey("IdCourseSection");

                    b.HasIndex("IdAnnounce");

                    b.ToTable("sectiuni_curs", (string)null);
                });

            modelBuilder.Entity("backend.Models.Utils.SectionContent", b =>
                {
                    b.Property<int>("IdSectionContent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasColumnName("id_continut_sectiune");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSectionContent"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("continut");

                    b.Property<int>("IdCourseSection")
                        .HasColumnType("int")
                        .HasColumnName("id_sectiune_curs");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("ordine");

                    b.HasKey("IdSectionContent");

                    b.HasIndex("IdCourseSection");

                    b.ToTable("continut_sectiune", (string)null);
                });

            modelBuilder.Entity("backend.Models.User.MemberQuality", b =>
                {
                    b.HasOne("backend.Models.User.Account", "Member")
                        .WithMany("Qualities")
                        .HasForeignKey("IdMember")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User.Quality", "Quality")
                        .WithMany("MemberQualities")
                        .HasForeignKey("IdQuality")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Quality");
                });

            modelBuilder.Entity("backend.Models.User.OperationPlace", b =>
                {
                    b.HasOne("backend.Models.User.Account", "Account")
                        .WithMany("OperationPlaces")
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User.Location", "Location")
                        .WithMany("OperationPlaces")
                        .HasForeignKey("IdLocation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("backend.Models.User.RememberUser", b =>
                {
                    b.HasOne("backend.Models.User.Account", "CurrentUserSession")
                        .WithOne("RememberUserSession")
                        .HasForeignKey("backend.Models.User.RememberUser", "IdAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentUserSession");
                });

            modelBuilder.Entity("backend.Models.Utils.CourseSection", b =>
                {
                    b.HasOne("backend.Models.Utils.Announce", "SectionAnnounce")
                        .WithMany("CourseSections")
                        .HasForeignKey("IdAnnounce")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectionAnnounce");
                });

            modelBuilder.Entity("backend.Models.Utils.SectionContent", b =>
                {
                    b.HasOne("backend.Models.Utils.CourseSection", "CourseSectionContent")
                        .WithMany("SectionContents")
                        .HasForeignKey("IdCourseSection")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseSectionContent");
                });

            modelBuilder.Entity("backend.Models.User.Account", b =>
                {
                    b.Navigation("OperationPlaces");

                    b.Navigation("Qualities");

                    b.Navigation("RememberUserSession");
                });

            modelBuilder.Entity("backend.Models.User.Location", b =>
                {
                    b.Navigation("OperationPlaces");
                });

            modelBuilder.Entity("backend.Models.User.Quality", b =>
                {
                    b.Navigation("MemberQualities");
                });

            modelBuilder.Entity("backend.Models.Utils.Announce", b =>
                {
                    b.Navigation("CourseSections");
                });

            modelBuilder.Entity("backend.Models.Utils.CourseSection", b =>
                {
                    b.Navigation("SectionContents");
                });
#pragma warning restore 612, 618
        }
    }
}
